repos:
  - repo: local
    hooks:
      - id: eslint
        name: ESLint
        entry: npm run lint:check
        language: system
        types: [file]
        files: \.(ts|html)$
        pass_filenames: false

      - id: prettier
        name: Prettier
        entry: npm run format:check
        language: system
        pass_filenames: false
      
      - id: tsc
        name: Type check
        entry: npm run typecheck
        language: system
        types: [file]
        files: \.(ts)$
        pass_filenames: false
  
  - repo: https://github.com/gitleaks/gitleaks
    rev: v8.30.1
    hooks:
      - id: gitleaks