sonar.projectKey=NoTIPswe_notip-simulator-frontend
sonar.organization=notipswe

sonar.sources=cmd,internal
sonar.exclusions=**/*_test.go,vendor/**

sonar.tests=.
sonar.test.inclusions=**/*_test.go

sonar.go.coverage.reportPaths=coverage.out
