sonar.projectKey=NoTIPswe_notip-simulator-frontend
sonar.organization=notipswe

sonar.sources=src
sonar.exclusions=**/*.spec.ts, src/environments/**, src/generated/**

sonar.tests=src
sonar.test.inclusions=**/*.spec.ts

sonar.javascript.lcov.reportPaths=coverage/lcov.info
sonar.testExecutionReportPaths=coverage/test-reporter.xml
sonar.eslint.reportPaths=eslint-report.json
sonar.typescript.tsconfigPath=tsconfig.json